use_frameworks!

platform :ios, '11.0'
install! 'cocoapods',
  disable_input_output_paths: true,
  generate_multiple_pod_projects: true,
  # integrate_targets: false,
  deterministic_uuids: false
  # incremental_installation: true,

target 'DJRSwiftResource_Example' do
  pod 'DJRSwiftResource', :path => '../'

  pod 'R.swift', '~>7.3'

  target 'DJRSwiftResource_Tests' do
    inherit! :search_paths


  end
end
