use_frameworks!
inhibit_all_warnings!
platform :ios, '14.0'
install! 'cocoapods',
           disable_input_output_paths: true,
           generate_multiple_pod_projects: true,
           deterministic_uuids: false

target 'LXSwiftUIKit_Example' do
  pod 'LXSwiftUIKit', :path => '../'

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      if target.name == 'RxSwift'
       target.build_configurations.each do |config|
          if config.name == 'Debug'
             config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
          end
       end
      end
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end
end
