use_frameworks!
# use_modular_headers!
ENV['SWIFT_VERSION'] = '5'
platform :ios, '17.0'
install! 'cocoapods',
           disable_input_output_paths: true,
           generate_multiple_pod_projects: true,
          #  integrate_targets: false,
           deterministic_uuids: false

target 'DJTest' do
  inherit! :search_paths

  # pod 'DJObjcModule', :path => '../DJObjcModule'
  # pod 'DJSwiftModule', :path => '../DJSwiftModule'
  # pod 'LXToolKit', :path => '../LXToolKit'
  # pod 'LXToolKitObjC', :path => '../LXToolKitObjC'
  # pod 'DJBusinessModuleSwift', :path => '../../../BL.repo/DaoJia/DJBusinessModuleSwift'
	# pod 'Masonry'
  # pod 'Moya-ObjectMapper/RxSwift', :git => 'https://github.com/p-rob/Moya-ObjectMapper.git', :branch => 'master'  # https://github.com/ivanbruel/Moya-ObjectMapper
  # pod 'RxNetworks'#, :modular_headers => true

  # pod 'YYText'
  # pod 'MJRefresh'
  # pod 'Action'
  # pod 'YPImagePicker'
  # pod 'GoogleMobileAds'
  # pod 'FirebaseAnalytics'
  # pod 'MJExtension'
  # pod 'Mantle'
  # pod 'FirebaseCrashlytics'
  # pod 'ObjectMapper'
  pod 'R.swift', '~> 7.0'
  # pod 'DJObjcModule', :path => '../DJObjcModule'
  # pod 'DJSwiftModule', :path => '../DJSwiftModule'
  # pod 'DJRSwiftTest', :path => '../DJRSwiftTest'
  # pod 'DJBusinessModuleSwift', :path => '../DJBusinessModuleSwift'
  pod 'DJRSwiftResource', :path => '../DJRSwiftResource'

  # pod 'LXSwiftUIKit', :path => '../LXSwiftUIKit'

  pod 'LXToolKit_Example', :path => '../LXToolKit_Example'
  pod 'LXToolKitObjC_Example', :path => '../LXToolKitObjC_Example'

  pod 'LXToolKit', :path => '../LXToolKit'
  pod 'LXToolKitObjC', :path => '../LXToolKitObjC'

  pod 'Moya-ObjectMapper/RxSwift', :git => 'https://github.com/p-rob/Moya-ObjectMapper.git', :branch => 'master'
  pod 'FLEX', :configurations => ['Debug']

  # RxNetworks
  # pod 'YYCache', :git => 'git@github.com:ibireme/YYCache.git'
  # pod 'MBProgressHUD', :git => 'git@github.com:jdg/MBProgressHUD.git'
  #pod 'RxNetworks', '~>0.4'
  # pod 'RxSwiftExt', '~> 6.2'
  pod 'RxSwiftExt', :git => 'git@github.com:RxSwiftCommunity/RxSwiftExt.git', :tag => '6.2.0'

end

# static_frameworks = [
#   # 'DJBusinessModuleSwift',
#   'RxNetworks',
#   # 'Toast-Swift', 'HandyJSON', 'Moya', 'RxSwift', 'Alamofire',
#   # 'FirebaseCrashlytics',
#   # 'FirebaseCore',
#   # 'GoogleUtilities', 'PromisesObjC',
#   # 'FirebaseCoreDiagnostics', 'GoogleDataTransport', 'nanopb',
#   # 'FirebaseCoreInternal',
#   # 'FirebaseInstallations',
#   ]
#   pre_install do |installer|
#     installer.pod_targets.each do |pod|
#       # 注意这里和上面的不同
#       if !static_frameworks.include?(pod.name)
#         def pod.static_framework?;
#           true
#         end
#         def pod.build_type;
#           Pod::BuildType.static_library
#         end
#       end
#     end
#   end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        # config.build_settings['IPHONEOgS_DEPLOYMENT_TARGET'] = '17.0'
      end
      if target.name == 'RxSwift'
       target.build_configurations.each do |config|
          if config.name == 'Debug'
             config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
          end
       end
      end
      # elsif target.name == 'LXSwiftUIKit'
      #   target.build_configurations.each do |config|
      #     config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      #     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      #   end
      # else
      #   target.build_configurations.each do |config|
      #     config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      #     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      #   end
      # end
    end
  end
end

pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
	Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
