ENV['SWIFT_VERSION'] = '5'
use_frameworks!
inhibit_all_warnings!
platform :ios, '13.0'

target 'DJObjcModule_Example' do
  pod 'DJObjcModule', :path => '../'
  pod 'DJSwiftModule', :path => '../../DJSwiftModule'
  pod 'DJBusinessModuleSwift', :path => '../../../../BL.repo/DaoJia/DJBusinessModuleSwift'

  pod 'RxSwift'
  pod 'Moya-ObjectMapper/RxSwift', :git => 'https://github.com/p-rob/Moya-ObjectMapper.git', :branch => 'master'  # https://github.com/ivanbruel/Moya-ObjectMapper


  target 'DJObjcModule_Tests' do
    inherit! :search_paths


  end
end

post_install do |installer|
  static_frameworks = ['DJBusinessModuleSwift', 'RxNetworks', 'Toast-Swift', 'HandyJSON', 'Moya', 'RxSwift', 'Alamofire', 'Lemons'
    # 'FirebaseCrashlytics',
    # 'FirebaseCore',
    # 'GoogleUtilities', 'PromisesObjC',
    # 'FirebaseCoreDiagnostics', 'GoogleDataTransport', 'nanopb',
    # 'FirebaseCoreInternal',
    # 'FirebaseInstallations',
  ]
  # pre_install do |installer|
  #   installer.pod_targets.each do |pod|
  #     # 注意这里和上面的不同
  #     if !static_frameworks.include?(pod.name)
  #       def pod.static_framework?;
  #         true
  #       end
  #       def pod.build_type;
  #         Pod::BuildType.static_library
  #       end
  #     end
  #   end
  # end

  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
