use_frameworks!

platform :ios, '13.0'
install! 'cocoapods',
           disable_input_output_paths: true,
           generate_multiple_pod_projects: true,
           deterministic_uuids: false

target 'LXToolKitObjC_Example_Example' do
  pod 'LXToolKitObjC_Example', :path => '../'
  pod 'LXToolKitObjC', :path => '../../LXToolKitObjC'

  target 'LXToolKitObjC_Example_Tests' do
    inherit! :search_paths


  end
end

# avoid_warning_list = []
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        # print('>>>[2]: ', target, "\tconfig: ", config, "\n")
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        # if avoid_warning_list.include?(target.name)
        #   config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'NO'
        #   config.build_settings['GCC_WARN_UNUSED_VARIABLE'] = 'NO'
        # else
        #   config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
        #   config.build_settings['GCC_WARN_UNUSED_VARIABLE'] = 'YES'
        # end
      end
    end
  end
end
