use_frameworks!

platform :ios, '13.0'
ENV['SWIFT_VERSION'] = '5'

target 'LXToolKit_Example_Example' do
  pod 'LXToolKit_Example', :path => '../'
  pod 'LXToolKit', :path => '../../LXToolKit', :subspec => ['Core', '3rd']
  pod 'DJTestKit', :path => '../../DJTestKit'

  pod 'Moya-ObjectMapper/RxSwift', :git => 'https://github.com/p-rob/Moya-ObjectMapper.git', :branch => 'master'
  pod 'FLEX', :configurations => ['Debug']

  target 'LXToolKit_Example_Tests' do
    inherit! :search_paths


  end
end

# avoid_warning_list = []
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        # print('>>>[2]: ', target, "\tconfig: ", config, "\n")
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        # if avoid_warning_list.include?(target.name)
        #   config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'NO'
        #   config.build_settings['GCC_WARN_UNUSED_VARIABLE'] = 'NO'
        # else
        #   config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
        #   config.build_settings['GCC_WARN_UNUSED_VARIABLE'] = 'YES'
        # end
      end
    end
  end
end

pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
	Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
